spring:
  application:
    name: doctors-service

  datasource:
    url: jdbc:postgresql://users-db:5432/${db_name}
    username: ${db_user}
    password: ${db_password}

jwt:
  secret-key: ${secret_key}
  # 4 hours
  expiration-time: 14400000

server:
  port: ${port}

logging:
  level:
    org.springframework: TRACE