spring:
  application:
    name: appointments-service

  datasource:
    url: jdbc:postgresql://app-db:5432/${db_name}
    username: ${db_user}
    password: ${db_password}

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret-key: ${secret_key}
  # 4 hours
  expiration-time: 14400000

kafka:
  bootstrap-address: ${kafka_address}
  topic: appointment

server:
  port: ${port}

#logging:
#  level:
#    org.springframework: TRACE